// Metro Quest — pixel art de respaldo pintado en código (las 29 criaturas canon v1)
// y sus gritos afinados a mano. El motor los usa cuando falta el PNG 64x64.
(() => {
  const MQ = (globalThis.MQ = globalThis.MQ || {});
  MQ.FALLBACK_ART = {
    frontinito: {
      pal: {"k":"#1e1410","f":"#3a2a1e","w":"#e8dfc8","e":"#1a1a1a"},
      art: [
        "...kk......kk...",
        "..kffk....kffk..",
        "..kfffkkkkfffk..",
        ".kffffffffffffk.",
        ".kfwwfffffwwffk.",
        ".kfwewffffwewfk.",
        ".kfwwfffffwwffk.",
        ".kffffwwwwffffk.",
        "..kfffwkkwfffk..",
        "..kffffffffffk..",
        ".kffkffffffkffk.",
        "..kk..kkkk..kk..",
      ],
    },
    ucumari: {
      pal: {"k":"#1e1410","f":"#3a2a1e","w":"#e8dfc8","e":"#1a1a1a"},
      art: [
        "...kk......kk...",
        "..kffk....kffk..",
        ".kffffkkkkffffk.",
        ".kfwwffffffwwfk.",
        ".kfwewffffwewfk.",
        ".kfwwffffffwwfk.",
        "..kfffwwwwfffk..",
        "..kffffwwffffk..",
        ".kffffffffffffk.",
        "kffkffffffffkffk",
        "kffkffffffffkffk",
        ".kffffffffffffk.",
        "..kffkkkkkkffk..",
        "..kkk......kkk..",
      ],
    },
    turpialin: {
      pal: {"k":"#1c1c1c","o":"#f5a623","w":"#ffffff","b":"#d98a2b","e":"#f2ead8"},
      art: [
        "......kkkk......",
        ".....kkkkkk.....",
        "....kkekkkkk....",
        "....kkkkkkkbb...",
        "...kkkkkkkk.....",
        "..kooookkk......",
        ".koooooookw.....",
        ".kooooooookww...",
        ".koooooooook....",
        "..koooooook.....",
        "...koookok......",
        "....kk..kk......",
      ],
    },
    cantaclaro: {
      pal: {"k":"#1c1c1c","o":"#f5a623","w":"#ffffff","h":"#c9a36a","b":"#d98a2b","e":"#f2ead8","n":"#ffffff"},
      art: [
        "....hhhhhhhh....",
        "..hhhhhhhhhhhh..",
        "....kkkkkkk.....",
        "...kkekkkkkbb..n",
        "...kkkkkkkb..n..",
        "..koooookk......",
        ".kooooooook..n..",
        ".koowwwooook....",
        ".kooooooooook...",
        "..kooooooook....",
        "...kooooko......",
        "....kk..kk......",
      ],
    },
    cocuyin: {
      pal: {"k":"#202830","c":"#3a4a55","y":"#ffe66e","e":"#ffffff"},
      art: [
        "....kkkkkkk.....",
        "...kcecccecck...",
        "..kccccccccck...",
        ".kccccccccccck..",
        ".kccccccccccck..",
        "..kccccccccck...",
        "...kkcccccck....",
        "....kyyyyyk.....",
        "...kyyyyyyyk....",
        "....yyyyyyy.....",
        ".....yyyyy......",
        "......yyy.......",
      ],
    },
    centella: {
      pal: {"k":"#1a1a2e","y":"#ffe66e","o":"#f5a623","w":"#ffffff","e":"#1a1a2e"},
      art: [
        "......yy...w....",
        ".w...yyyy.......",
        "....yyyyyy...y..",
        ".y..yyooyyy.....",
        "..yyoooooyyy....",
        ".yyoeoooeooyy...",
        "..yyoooooyy..w..",
        ".w.yyokkooyyy...",
        "...yyoooooy.....",
        "..y.yyyyyy..y...",
        "......yyy.......",
        ".....y..y.......",
      ],
    },
    chigui: {
      pal: {"k":"#3a2a1a","b":"#a8784a","e":"#222222","n":"#d9a36a"},
      art: [
        "....kkkkkkkk....",
        "...kbbbbbbbbk...",
        "..kbbbbbbbbbbk..",
        ".kbebbbbbbbbbkk.",
        ".kbbbbbbbbbbbbnk",
        ".kbbbbbbbbbbbnnk",
        ".kbbbbbbbbbbbbk.",
        ".kbbbbbbbbbbbk..",
        "..kbbkbbkbbbk...",
        "..kbk.kbk.kbk...",
      ],
    },
    chiguiron: {
      pal: {"k":"#3a2a1a","b":"#a8784a","s":"#8a8a96","e":"#222222","n":"#d9a36a"},
      art: [
        "....sssssss.....",
        "..ssksssskss....",
        "..ksssssssssk...",
        ".kbssssssssssk..",
        ".kbebbbbbbbbbkk.",
        "kbbbbbbbbbbbbbnk",
        "kbbbbbbbbbbbbnnk",
        ".kbbbbbbbbbbbbk.",
        ".kbbbbbbbbbbbk..",
        "..kbbkbbkbbbk...",
        "..kbk..kbk.kbk..",
      ],
    },
    cunaguaro: {
      pal: {"k":"#241a0e","o":"#d9a04a","s":"#3a2a1a","w":"#f2ead8","e":"#d9d92b"},
      art: [
        "..kk.......kk...",
        ".kook.....kok...",
        ".koookkkkkook...",
        ".koeooooooeok...",
        ".kooowwwwooook..",
        "..koowkkwook....",
        "..koooooooookk..",
        ".koosooswoosokk.",
        ".kowoosowoooosk.",
        ".kosoowoosook.k.",
        "..koook.koook...",
        "..kok.k.kok.k...",
      ],
    },
    pereza: {
      pal: {"k":"#2a241a","g":"#8a8468","f":"#c9bda0","m":"#3a2d1e","e":"#222222"},
      art: [
        "....kkkkkkk.....",
        "...kgggggggk....",
        "..kgfffffffgk...",
        "..kgfmefemfgk...",
        "..kgfffffffgk...",
        "..kgffkkkffgk...",
        "...kggggggggk...",
        "..kgggggggggk...",
        ".kggkgggggkggk..",
        ".kggkgggggkggk..",
        "..kgggggggggk...",
        "...kgg...ggk....",
      ],
    },
    rabipelado: {
      pal: {"k":"#1e1a16","g":"#9a9a96","w":"#e8e0d4","p":"#d9a0a0","e":"#1a1a1a"},
      art: [
        "..kk............",
        ".kwwk....kk.....",
        ".kwwwkkkkggk....",
        ".kwewwgggggggk..",
        "..kwwwggggggggk.",
        "..kpkwggggggggk.",
        "...k.kggggggkpp.",
        "....kggggggkp...",
        "....kgkggkggk.p.",
        "....kk.kk.kk.pp.",
      ],
    },
    tonina: {
      pal: {"k":"#3a1e28","p":"#d98aa0","w":"#f2c9d4","e":"#222222"},
      art: [
        "......kkkk......",
        "....kkppppkk....",
        "..kkppppppppk...",
        ".kpppeppppppkk..",
        "kkppppppppppppk.",
        "kpwwwwpppppppppk",
        ".kpwwwwppppkppk.",
        "..kppppppppkpkk.",
        "...kkppppkkppk..",
        ".....kkkk..kk...",
      ],
    },
    guacamayo: {
      pal: {"k":"#1c1c1c","r":"#d9342b","b":"#2b6bd9","y":"#f5d76e","w":"#ffffff","e":"#222222"},
      art: [
        ".....kkkk.......",
        "....krrrrkk.....",
        "...krrrrrkww....",
        "...krrrrekww....",
        "...krrrrrkkk....",
        "..krrrrrkk......",
        ".kryyrrrrk......",
        ".kryyrrrrbk.....",
        ".krrrrrrbbk.....",
        "..krrrrbbbk.....",
        "...krrrbbk......",
        "....krrbk.......",
        ".....kbbk.......",
        "....kk..kk......",
      ],
    },
    caribito: {
      pal: {"k":"#1c2a33","s":"#6b8fa8","r":"#d9544a","w":"#ffffff","e":"#ffe66e"},
      art: [
        "....kkkkkk......",
        "..kkssssssk.k...",
        ".kssssssssskkk..",
        "ksseksssssssskk.",
        "kssssssssssssk..",
        "kswswswsssskkk..",
        ".krrrrrrssk.kk..",
        "..kkrrrssk...k..",
        "....kkkkk.......",
      ],
    },
    caribazo: {
      pal: {"k":"#1c2a33","s":"#6b8fa8","r":"#d9544a","w":"#ffffff","e":"#ffe66e"},
      art: [
        ".....kkkkkkk....",
        "...kkssssssssk..",
        "..kssssssssssskk",
        ".ksseksssssssssk",
        ".kssssssssssssskk",
        "kswkwkwkwsssssk.",
        "kskwkwkwkssssskk",
        ".krrrrrrrrssk...",
        "..kkrrrrrrsk.k..",
        "....kkkkkkk.kk..",
      ],
    },
    araguako: {
      pal: {"k":"#3a1a0a","r":"#b54a2a","t":"#d9824a","m":"#3a1a0a","e":"#222222"},
      art: [
        "....kkkkkkk.....",
        "...krrrrrrrk....",
        "..krtttttttrk...",
        "..krtetttetrk...",
        "..krtttmtttrk...",
        "..krttmmmttrk...",
        "...krrtmtrrk....",
        "..krrrrrrrrkk...",
        ".krrkrrrrkrrk.r.",
        ".krk.rrrr.krk.r.",
        "..k.krrrrk..krr.",
        "....krr.rk......",
        "....kk..kk......",
      ],
    },
    bachaquito: {
      pal: {"k":"#2a1208","r":"#c9502b","g":"#5e8b3f","e":"#ffe66e"},
      art: [
        "..gg............",
        ".gggg...........",
        "..gg.k...k......",
        "...kk.k.k.......",
        "..kerk.krrk.....",
        "..krrkkrrrk.....",
        "...krrrrrrk.....",
        "..krrkrrrrk.....",
        ".k.krrrrk.k.....",
        "..k.kkkk.k......",
      ],
    },
    bachacon: {
      pal: {"k":"#2a1208","r":"#c9502b","g":"#5e8b3f","e":"#ffe66e"},
      art: [
        ".gggggg.........",
        "gggggggg........",
        ".gggggg.........",
        "..ggg.kk...kk...",
        "...kkk.k.k.k....",
        "..kerrk.krrrk...",
        ".krrrrkkrrrrrk..",
        ".krrrrrrrrrrrk..",
        "..krrrkrrrrrk...",
        ".k.krrrrrrk.k...",
        "..k.kkkkkk.k....",
      ],
    },
    cachicamo: {
      pal: {"k":"#3a2d1e","a":"#b09a6a","d":"#8a754a","p":"#d9b38c","e":"#222222"},
      art: [
        ".....kkkkkkk....",
        "....kaaaaaaak...",
        "...kaadaadaaak..",
        "..kaaadaadaaaak.",
        "..kaaadaadaaaak.",
        ".kaaaadaadaaaak.",
        "kpaaaaaaaaaaaak.",
        "kpekaaaaaaaakk..",
        "kppk.kaaaaak....",
        ".kk..kk..kk.....",
      ],
    },
    morrocoy: {
      pal: {"k":"#2d2416","g":"#5e6b35","y":"#f5d76e","p":"#c9a36a","e":"#222222"},
      art: [
        ".....kkkkkkk....",
        "....kgyggygk....",
        "..kkgyggyggykk..",
        ".kygygyggygygk..",
        ".kgyggyggyggyk..",
        ".kkkkkkkkkkkkk..",
        "kpek.kppk.kppk..",
        "kppk..kk...kk...",
        ".kk.............",
      ],
    },
    mapanare: {
      pal: {"k":"#241a0e","n":"#8a6a3a","d":"#5a4226","e":"#d9d92b","t":"#d9342b"},
      art: [
        "......kkkkk.....",
        ".....knnnnnk....",
        "....knnednnnk...",
        "....knnnnnnkt...",
        ".....knnnnk.t...",
        "..kkkknnnnk.....",
        ".knnnnnnnnk.....",
        "knndnnnndnnk....",
        "knnnnnnnnnnk....",
        ".knndnnnndnk....",
        "..kknnnnnnk.....",
        "....kkkkkk......",
      ],
    },
    duendecito: {
      pal: {"k":"#1e1810","h":"#b5300a","f":"#d9a36a","c":"#4a6741","w":"#f2ead8","e":"#222222"},
      art: [
        ".......kk.......",
        "......khhk......",
        ".....khhhhk.....",
        "....khhhhhhk....",
        "...khhhhhhhhk...",
        "...kffeffefk....",
        "....kffffk......",
        "...kcccccck.....",
        "..kcckccckck....",
        "...kccccck......",
        "...kck..kck.....",
        "..kwwk...k......",
      ],
    },
    pavoso: {
      pal: {"k":"#241a33","p":"#6a4a8a","d":"#4a3266","e":"#d9d92b"},
      art: [
        "....kkkkkkk.....",
        "..kkpppppppkk...",
        ".kpppppppppppk..",
        ".kpeppppppepppk.",
        ".kppppkkpppppk..",
        ".kpppppppppppk..",
        "..kpdpdpdpdpk...",
        "..kppdpdpdppk...",
        "...kpppppppk....",
        "..k.kpppppk.k...",
        ".....kkkkk......",
      ],
    },
    vagonima: {
      pal: {"k":"#2a2a3a","s":"#c9c9d4","o":"#e85a1a","w":"#aaeeff","e":"#222222"},
      art: [
        "..kkkkkkkkkkkk..",
        ".kssssssssssssk.",
        ".kswwkswwkswwsk.",
        ".kswwkswwkswwsk.",
        ".kssssssssssssk.",
        ".kooooooooooook.",
        ".kssssssssssssk.",
        "..kssssssssssk..",
        "...ss.ssss.ss...",
        "....s..ss..s....",
        ".....s....s.....",
      ],
    },
    llorona: {
      pal: {"k":"#1e1e2e","w":"#e8e8f0","f":"#cfcfe0","b":"#8888c9","e":"#222222"},
      art: [
        ".....kkkkkk.....",
        "....kwwwwwwk....",
        "...kwwwwwwwwk...",
        "...kwffffffwk...",
        "...kwfefeffwk...",
        "...kwffffffwk...",
        "...kwffkkffwk...",
        "..kwwffffffwwk..",
        "..kwwwwwwwwwwk..",
        ".b.kwwwwwwwwk.b.",
        ".b.kwwwwwwwwk.b.",
        "..b.kwwwwwwk.b..",
        "....kwwwwwwk....",
        ".....kkkkkk.....",
      ],
    },
    sayona: {
      pal: {"k":"#111118","h":"#1c1c28","f":"#e0d4c9","e":"#d9342b","d":"#2a2a3a"},
      art: [
        "....kkkkkkkk....",
        "...khhhhhhhhk...",
        "..khhffffffhhk..",
        "..khhfefeffhhk..",
        "..khhffffffhhk..",
        "..khhhfkkfhhhk..",
        "..khhdddddhhhk..",
        "..khdddddddhk...",
        "..khdddddddhk...",
        "...kdddddddk....",
        "...kdddddddk....",
        "..kdddddddddk...",
        "..kdddddddddk...",
        "...kkkkkkkkk....",
      ],
    },
    silbon: {
      pal: {"k":"#15151c","h":"#3a3226","f":"#cfc0a8","d":"#26262e","s":"#8a754a","e":"#ffffff"},
      art: [
        ".....hhhhhh.....",
        "...hhhhhhhhhh...",
        ".....kffffk.....",
        ".....kfefek.....",
        ".....kffffk.....",
        "......kffk......",
        "....kkddddkk....",
        "...kd.kddk.dk...",
        "...k..kddk..k...",
        "..ss..kddk......",
        ".ssss.kddk......",
        ".ssss.kdkdk.....",
        "..ss..kk.kk.....",
        "......k...k.....",
      ],
    },
    catatumbo: {
      pal: {"k":"#2a2a3a","c":"#5a6a7a","w":"#3b6b8c","y":"#ffe66e","e":"#ffffff"},
      art: [
        "...kkkkkkkkkk...",
        "..kcccccccccck..",
        ".kcccccccccccck.",
        ".kccecccccecck..",
        "..kcccccccccck..",
        "...kkkkkkkkkk...",
        "....y...y..y....",
        "...yy..yy..y....",
        "...y...y..yy....",
        "..yy..yy..y.....",
        "..wwwwwwwwwww...",
        ".wwwwwwwwwwwww..",
      ],
    },
    trenfantasma: {
      pal: {"k":"#0e0e16","s":"#3a3a4a","o":"#e85a1a","w":"#ffe66e","g":"#7affc9","e":"#222222"},
      art: [
        "...kkkkkkkkkk...",
        "..kssssssssssk..",
        ".kskwwkssskwwsk.",
        ".kskwwkssskwwsk.",
        ".kssssssssssssk.",
        ".ksoooooooooosk.",
        ".kssssksksssssk.",
        ".kssssssssssssk.",
        ".kskgks..kgkssk.",
        "..kwk......kwk..",
        ".gg.g.gggg.g.gg.",
        "..g..gg..gg..g..",
      ],
    },
  };

  // Gritos afinados a mano (canon v1). Los demás se generan en dex.js.
  MQ.CRIES_CANON = {
    frontinito: [["b",180,0.12,"sawtooth",0.06,0,-40],["b",140,0.2,"triangle",0.05,0.1,-30]],
    ucumari: [["n",0.15,0.04,0],["b",95,0.35,"sawtooth",0.07,0,-25],["b",70,0.3,"triangle",0.05,0.25,-15]],
    turpialin: [["b",1568,0.08,"square",0.045,0,0],["b",1864,0.08,"square",0.045,0.09,0],["b",1318,0.1,"square",0.045,0.18,0],["b",2093,0.12,"square",0.04,0.3,-200]],
    cantaclaro: [["b",1318,0.08,"square",0.05,0,0],["b",1568,0.08,"square",0.05,0.09,0],["b",1046,0.08,"square",0.05,0.18,0],["b",1568,0.1,"square",0.05,0.27,0],["b",2093,0.14,"square",0.045,0.38,-300]],
    cocuyin: [["b",1200,0.06,"square",0.05,0,300],["b",1500,0.08,"square",0.04,0.08,400]],
    centella: [["n",0.12,0.06,0],["b",880,0.18,"sawtooth",0.05,0,-500],["b",1760,0.1,"square",0.03,0.12,-800]],
    chigui: [["b",950,0.07,"sine",0.06,0,150],["b",1100,0.07,"sine",0.06,0.09,150],["b",900,0.1,"sine",0.05,0.18,-100]],
    chiguiron: [["b",600,0.1,"sine",0.06,0,100],["b",500,0.12,"sine",0.06,0.12,-80],["b",90,0.25,"triangle",0.05,0.2,-20]],
    cunaguaro: [["n",0.1,0.05,0],["b",520,0.18,"sawtooth",0.055,0,-260]],
    pereza: [["b",420,0.35,"sine",0.05,0,-160],["b",250,0.25,"sine",0.04,0.3,-60]],
    rabipelado: [["n",0.22,0.06,0],["b",320,0.2,"sawtooth",0.04,0,-90]],
    guacamayo: [["n",0.08,0.05,0],["b",900,0.12,"sawtooth",0.06,0,-350],["n",0.08,0.05,0.14],["b",850,0.12,"sawtooth",0.06,0.14,-300]],
    caribito: [["b",700,0.06,"square",0.05,0,-200],["n",0.05,0.05,0.05]],
    caribazo: [["b",500,0.08,"square",0.06,0,-250],["n",0.07,0.06,0.07],["b",400,0.08,"square",0.06,0.14,-200],["n",0.07,0.06,0.2]],
    araguako: [["b",110,0.5,"sawtooth",0.06,0,30],["b",165,0.4,"sawtooth",0.04,0.1,20],["n",0.3,0.02,0.15]],
    tonina: [["b",1800,0.12,"sine",0.05,0,700],["n",0.03,0.04,0.15],["n",0.03,0.04,0.2],["b",2400,0.15,"sine",0.045,0.26,-500]],
    bachaquito: [["b",2000,0.03,"square",0.04,0,0],["b",2200,0.03,"square",0.04,0.05,0],["b",1900,0.03,"square",0.04,0.1,0]],
    bachacon: [["b",1200,0.04,"square",0.05,0,0],["b",1400,0.04,"square",0.05,0.06,0],["b",1100,0.04,"square",0.05,0.12,0],["b",400,0.1,"triangle",0.05,0.18,-50]],
    cachicamo: [["n",0.08,0.04,0],["b",260,0.1,"triangle",0.05,0.04,-60],["n",0.08,0.04,0.16]],
    morrocoy: [["b",150,0.3,"triangle",0.055,0,-50]],
    mapanare: [["n",0.3,0.05,0],["n",0.2,0.04,0.32]],
    duendecito: [["b",784,0.06,"triangle",0.05,0,0],["b",988,0.06,"triangle",0.05,0.07,0],["b",1318,0.09,"triangle",0.05,0.14,100]],
    pavoso: [["b",233,0.4,"sine",0.05,0,-60]],
    vagonima: [["b",1400,0.35,"sawtooth",0.035,0,-700],["b",660,0.12,"square",0.04,0.4,0],["b",523,0.12,"square",0.04,0.52,0]],
    llorona: [["b",660,0.3,"sine",0.055,0,220],["b",880,0.4,"sine",0.05,0.3,-330]],
    sayona: [["b",700,0.15,"sawtooth",0.05,0,500],["b",1200,0.3,"sawtooth",0.045,0.15,-600]],
    silbon: [["b",900,0.35,"sine",0.05,0,450],["b",1350,0.4,"sine",0.045,0.4,-550]],
    catatumbo: [["n",0.4,0.07,0],["b",75,0.5,"sawtooth",0.06,0,-25],["b",1800,0.08,"square",0.03,0.02,-900]],
    trenfantasma: [["b",220,0.7,"sawtooth",0.04,0,0],["b",262,0.7,"sawtooth",0.04,0,0],["n",0.5,0.03,0.1]],
  };
})();
