// Metro Quest — el Cuaderno de Espantos: tipos, movimientos y las 25 criaturas.
(() => {
  const MQ = (globalThis.MQ = globalThis.MQ || {});

  // ---- Tipos ---------------------------------------------------------------
  MQ.TYPES = {
    Criollo:   { color: '#b0a890' },
    Sabroso:   { color: '#e8a040' },
    Rumba:     { color: '#d94f8a' },
    Espanto:   { color: '#7a5ad9' },
    Catatumbo: { color: '#f5d76e' },
    Caribe:    { color: '#4a90d9' },
    Monte:     { color: '#5e8b3f' },
    Tepuy:     { color: '#9a8468' },
  };

  // atacante -> { defensor: multiplicador } (lo no listado es x1)
  MQ.CHART = {
    Criollo:   { Tepuy: 0.5 },
    Sabroso:   { Criollo: 2, Espanto: 0.5, Caribe: 0.5 },
    Rumba:     { Espanto: 2, Tepuy: 0.5, Rumba: 0.5 },
    Espanto:   { Criollo: 2, Rumba: 0.5, Tepuy: 0.5 },
    Catatumbo: { Caribe: 2, Rumba: 2, Tepuy: 0.5, Monte: 0.5 },
    Caribe:    { Tepuy: 2, Monte: 0.5, Catatumbo: 0.5, Caribe: 0.5 },
    Monte:     { Caribe: 2, Tepuy: 2, Sabroso: 0.5, Espanto: 0.5, Monte: 0.5 },
    Tepuy:     { Catatumbo: 2, Espanto: 2, Caribe: 0.5, Monte: 0.5 },
  };
  MQ.effect = (atk, defTypes) =>
    defTypes.reduce((m, t) => m * ((MQ.CHART[atk] || {})[t] ?? 1), 1);

  // ---- Movimientos ----------------------------------------------------------
  // fx: {heal:frac} cura al usuario; {stage:[stat,delta,'self'|'foe']} sube/baja.
  MQ.MOVES = {
    trancazo:    { name: 'Trancazo',              type: 'Criollo',   pow: 40,  acc: 100 },
    cachetada:   { name: 'Cachetada Criolla',     type: 'Criollo',   pow: 55,  acc: 95 },
    horapico:    { name: 'Empujón de Hora Pico',  type: 'Criollo',   pow: 75,  acc: 95 },
    abrazotia:   { name: 'Abrazo de Tía',         type: 'Criollo',   pow: 0,   acc: 100, fx: { heal: 0.5 } },
    gritomama:   { name: 'Regaño de Mamá',        type: 'Criollo',   pow: 0,   acc: 100, fx: { stage: ['atk', -1, 'foe'] } },
    arepazo:     { name: 'Arepazo',               type: 'Sabroso',   pow: 45,  acc: 100 },
    empanada:    { name: 'Empanada de Cazón',     type: 'Sabroso',   pow: 60,  acc: 100 },
    asadonegro:  { name: 'Asado Negro',           type: 'Sabroso',   pow: 80,  acc: 95 },
    hallacazo:   { name: 'Hallacazo Decembrino',  type: 'Sabroso',   pow: 95,  acc: 85 },
    abuela:      { name: 'Comida de Abuela',      type: 'Sabroso',   pow: 0,   acc: 100, fx: { heal: 0.5 } },
    cornetazo:   { name: 'Cornetazo',             type: 'Rumba',     pow: 40,  acc: 100 },
    tambor:      { name: 'Tambor de San Juan',    type: 'Rumba',     pow: 55,  acc: 100 },
    gaita:       { name: 'Gaita Furruquera',      type: 'Rumba',     pow: 70,  acc: 95 },
    joropo:      { name: 'Joropo Recio',          type: 'Rumba',     pow: 85,  acc: 90 },
    almallanera: { name: 'Alma Llanera',          type: 'Rumba',     pow: 105, acc: 80 },
    serenata:    { name: 'Serenata Caraqueña',    type: 'Rumba',     pow: 0,   acc: 100, fx: { stage: ['atk', -1, 'foe'] } },
    susto:       { name: 'Susto',                 type: 'Espanto',   pow: 40,  acc: 100 },
    maldeojo:    { name: 'Mal de Ojo',            type: 'Espanto',   pow: 0,   acc: 100, fx: { stage: ['atk', -1, 'foe'] } },
    pava:        { name: 'Pavita Negra',          type: 'Espanto',   pow: 0,   acc: 100, fx: { stage: ['def', -1, 'foe'] } },
    llanto:      { name: 'Llanto Eterno',         type: 'Espanto',   pow: 60,  acc: 100 },
    nocturno:    { name: 'Espanto Nocturno',      type: 'Espanto',   pow: 80,  acc: 95 },
    silbido:     { name: 'Silbido Lejano',        type: 'Espanto',   pow: 85,  acc: 1000 },
    ultimoviaje: { name: 'Último Viaje',          type: 'Espanto',   pow: 100, acc: 80 },
    chispazo:    { name: 'Chispazo',              type: 'Catatumbo', pow: 40,  acc: 100 },
    corrientazo: { name: 'Corrientazo',           type: 'Catatumbo', pow: 65,  acc: 100 },
    bajon:       { name: 'Bajón de Luz',          type: 'Catatumbo', pow: 0,   acc: 100, fx: { stage: ['spd', -1, 'foe'] } },
    tercerriel:  { name: 'Tercer Riel',           type: 'Catatumbo', pow: 80,  acc: 95 },
    catatumbazo: { name: 'Relámpago Catatumbo',   type: 'Catatumbo', pow: 105, acc: 80 },
    aguacerito:  { name: 'Aguacerito',            type: 'Caribe',    pow: 40,  acc: 100 },
    mordida:     { name: 'Mordida de Caribe',     type: 'Caribe',    pow: 55,  acc: 100 },
    paloagua:    { name: 'Palo de Agua',          type: 'Caribe',    pow: 70,  acc: 95 },
    crecida:     { name: 'Crecida del Guaire',    type: 'Caribe',    pow: 90,  acc: 85 },
    bejucazo:    { name: 'Bejucazo',              type: 'Monte',     pow: 45,  acc: 100 },
    hoja:        { name: 'Hoja Afilada',          type: 'Monte',     pow: 60,  acc: 100 },
    colmillo:    { name: 'Colmillo Mapanare',     type: 'Monte',     pow: 70,  acc: 95 },
    monteadentro:{ name: 'Monte Adentro',         type: 'Monte',     pow: 85,  acc: 90 },
    araguaney:   { name: 'Flor de Araguaney',     type: 'Monte',     pow: 0,   acc: 100, fx: { stage: ['atk', 1, 'self'] } },
    pedrada:     { name: 'Pedrada',               type: 'Tepuy',     pow: 45,  acc: 100 },
    conchazo:    { name: 'Conchazo',              type: 'Tepuy',     pow: 60,  acc: 100 },
    kueka:       { name: 'Piedra Kueka',          type: 'Tepuy',     pow: 0,   acc: 100, fx: { stage: ['def', 1, 'self'] } },
    temblor:     { name: 'Temblorcito',           type: 'Tepuy',     pow: 70,  acc: 95 },
    avalancha:   { name: 'Derrumbe del Ávila',    type: 'Tepuy',     pow: 85,  acc: 90 },
    tepuyazo:    { name: 'Peso del Tepuy',        type: 'Tepuy',     pow: 95,  acc: 85 },
  };

  // ---- Especies --------------------------------------------------------------
  // base: hp/atk/def/spd · catch: 0-255 (mayor = más fácil) · learn: [nivel, mov]
  MQ.SPECIES = {
    arepito: {
      name: 'Arepito', types: ['Sabroso'],
      base: { hp: 52, atk: 60, def: 60, spd: 53 }, catch: 60,
      learn: [[1, 'arepazo'], [1, 'trancazo'], [7, 'abuela'], [12, 'empanada'], [19, 'asadonegro'], [27, 'horapico'], [34, 'hallacazo']],
      evolve: { lvl: 16, to: 'pepiada' },
      dex: 'Nació en un budare a las 6 de la mañana. Calientico por dentro, tostadito por fuera. Si lo abrazas, te perdona todo.',
      pal: { k: '#3a2d1e', w: '#f2ead8', g: '#d9b36a', e: '#222222' },
      art: [
        '....kkkkkkkk....',
        '..kkwwwwwwwwkk..',
        '.kwwwwwwwwwwwwk.',
        '.kwwgwwwwwwgwwk.',
        'kwwwwwwwwwwwwwwk',
        'kwwekwwwwwwkewwk',
        'kwwwwwwwwwwwwwwk',
        'kwwwwwkkkkwwwwwk',
        '.kwwwwwwwwwwwwk.',
        '.kwwgwwwwwwgwwk.',
        '..kkwwwwwwwwkk..',
        '....kkkkkkkk....',
        '...kk......kk...',
      ],
    },
    pepiada: {
      name: 'Reina Pepiada', types: ['Sabroso', 'Criollo'],
      base: { hp: 72, atk: 82, def: 80, spd: 70 }, catch: 40,
      learn: [[1, 'arepazo'], [1, 'trancazo'], [7, 'abuela'], [12, 'empanada'], [19, 'asadonegro'], [27, 'horapico'], [34, 'hallacazo']],
      dex: 'Coronada en 1955 en honor a una reina de belleza. Lleva el aguacate como cetro. No se discute con ella: se le hace fila.',
      pal: { k: '#3a2d1e', w: '#f2ead8', g: '#7bb05a', y: '#f5d76e', e: '#222222' },
      art: [
        '...y..y..y..y...',
        '...yyyyyyyyyy...',
        '....kkkkkkkk....',
        '..kkwwwwwwwwkk..',
        '.kwwwwwwwwwwwwk.',
        'kwwekwwwwwwkewwk',
        'kwwwwwkkkkwwwwwk',
        '.kwwwwwwwwwwwwk.',
        '.kggggggggggggk.',
        'kggkggggggggkggk',
        '.kwwwwwwwwwwwwk.',
        '..kkwwwwwwwwkk..',
        '....kkkkkkkk....',
        '...kk......kk...',
      ],
    },
    turpialin: {
      name: 'Turpialín', types: ['Rumba'],
      base: { hp: 50, atk: 58, def: 50, spd: 68 }, catch: 60,
      learn: [[1, 'cornetazo'], [1, 'trancazo'], [7, 'serenata'], [12, 'tambor'], [19, 'gaita'], [26, 'joropo'], [36, 'almallanera']],
      evolve: { lvl: 16, to: 'cantaclaro' },
      dex: 'El pájaro nacional, pero chiquito y arrecho. Canta a las 5 a.m. sin pedir permiso, como las licuadoras de toda Venezuela.',
      pal: { k: '#1c1c1c', o: '#f5a623', w: '#ffffff', b: '#d98a2b', e: '#f2ead8' },
      art: [
        '......kkkk......',
        '.....kkkkkk.....',
        '....kkekkkkk....',
        '....kkkkkkkbb...',
        '...kkkkkkkk.....',
        '..kooookkk......',
        '.koooooookw.....',
        '.kooooooookww...',
        '.koooooooook....',
        '..koooooook.....',
        '...koookok......',
        '....kk..kk......',
      ],
    },
    cantaclaro: {
      name: 'Cantaclaro', types: ['Rumba', 'Monte'],
      base: { hp: 70, atk: 82, def: 64, spd: 90 }, catch: 40,
      learn: [[1, 'cornetazo'], [1, 'trancazo'], [7, 'serenata'], [12, 'tambor'], [19, 'gaita'], [26, 'joropo'], [30, 'monteadentro'], [36, 'almallanera']],
      dex: 'Turpial coplero con sombrero pelo e\' guama. Ganó un contrapunteo contra el mismísimo Diablo y desde entonces no hay quien lo calle.',
      pal: { k: '#1c1c1c', o: '#f5a623', w: '#ffffff', h: '#c9a36a', b: '#d98a2b', e: '#f2ead8', n: '#ffffff' },
      art: [
        '....hhhhhhhh....',
        '..hhhhhhhhhhhh..',
        '....kkkkkkk.....',
        '...kkekkkkkbb..n',
        '...kkkkkkkb..n..',
        '..koooookk......',
        '.kooooooook..n..',
        '.koowwwooook....',
        '.kooooooooook...',
        '..kooooooook....',
        '...kooooko......',
        '....kk..kk......',
      ],
    },
    cocuyin: {
      name: 'Cocuyín', types: ['Catatumbo'],
      base: { hp: 48, atk: 60, def: 48, spd: 72 }, catch: 60,
      learn: [[1, 'chispazo'], [1, 'trancazo'], [7, 'bajon'], [13, 'corrientazo'], [20, 'tercerriel'], [34, 'catatumbazo']],
      evolve: { lvl: 16, to: 'centella' },
      dex: 'Cocuyo de monte que se tragó un cable de alta tensión. Cuando se va la luz, todo el barrio lo busca. Él cobra en seriedad y cariño.',
      pal: { k: '#202830', c: '#3a4a55', y: '#ffe66e', e: '#ffffff' },
      art: [
        '....kkkkkkk.....',
        '...kcecccecck...',
        '..kccccccccck...',
        '.kccccccccccck..',
        '.kccccccccccck..',
        '..kccccccccck...',
        '...kkcccccck....',
        '....kyyyyyk.....',
        '...kyyyyyyyk....',
        '....yyyyyyy.....',
        '.....yyyyy......',
        '......yyy.......',
      ],
    },
    centella: {
      name: 'La Centella', types: ['Catatumbo', 'Espanto'],
      base: { hp: 66, atk: 88, def: 60, spd: 96 }, catch: 40,
      learn: [[1, 'chispazo'], [1, 'susto'], [7, 'bajon'], [13, 'corrientazo'], [20, 'tercerriel'], [24, 'nocturno'], [34, 'catatumbazo']],
      dex: 'La bola de fuego que persigue caminantes en la sabana. Dicen que si le rezas al revés se aleja. Nadie se acuerda del rezo al derecho.',
      pal: { k: '#1a1a2e', y: '#ffe66e', o: '#f5a623', w: '#ffffff', e: '#1a1a2e' },
      art: [
        '......yy...w....',
        '.w...yyyy.......',
        '....yyyyyy...y..',
        '.y..yyooyyy.....',
        '..yyoooooyyy....',
        '.yyoeoooeooyy...',
        '..yyoooooyy..w..',
        '.w.yyokkooyyy...',
        '...yyoooooy.....',
        '..y.yyyyyy..y...',
        '......yyy.......',
        '.....y..y.......',
      ],
    },
    chigui: {
      name: 'Chigüi', types: ['Caribe'],
      base: { hp: 56, atk: 46, def: 52, spd: 40 }, catch: 200,
      learn: [[1, 'trancazo'], [1, 'aguacerito'], [8, 'mordida'], [14, 'paloagua'], [22, 'crecida'], [28, 'horapico']],
      evolve: { lvl: 18, to: 'chiguiron' },
      dex: 'El Vaticano dictaminó que en Semana Santa cuenta como pescado. Él no fue consultado y prefiere no opinar del tema.',
      pal: { k: '#3a2a1a', b: '#a8784a', e: '#222222', n: '#d9a36a' },
      art: [
        '....kkkkkkkk....',
        '...kbbbbbbbbk...',
        '..kbbbbbbbbbbk..',
        '.kbebbbbbbbbbkk.',
        '.kbbbbbbbbbbbbnk',
        '.kbbbbbbbbbbbnnk',
        '.kbbbbbbbbbbbbk.',
        '.kbbbbbbbbbbbk..',
        '..kbbkbbkbbbk...',
        '..kbk.kbk.kbk...',
      ],
    },
    chiguiron: {
      name: 'Chigüirón', types: ['Caribe', 'Tepuy'],
      base: { hp: 82, atk: 70, def: 72, spd: 44 }, catch: 90,
      learn: [[1, 'trancazo'], [1, 'aguacerito'], [8, 'mordida'], [14, 'paloagua'], [20, 'conchazo'], [22, 'crecida'], [26, 'avalancha']],
      dex: 'Chigüire ancestral con lomo de piedra de tepuy. Se sienta donde le da la gana, incluyendo el tercer riel. El tercer riel se aguanta.',
      pal: { k: '#3a2a1a', b: '#a8784a', s: '#8a8a96', e: '#222222', n: '#d9a36a' },
      art: [
        '....sssssss.....',
        '..ssksssskss....',
        '..ksssssssssk...',
        '.kbssssssssssk..',
        '.kbebbbbbbbbbkk.',
        'kbbbbbbbbbbbbbnk',
        'kbbbbbbbbbbbbnnk',
        '.kbbbbbbbbbbbbk.',
        '.kbbbbbbbbbbbk..',
        '..kbbkbbkbbbk...',
        '..kbk..kbk.kbk..',
      ],
    },
    guacamayo: {
      name: 'Guacamayo', types: ['Rumba', 'Monte'],
      base: { hp: 60, atk: 66, def: 50, spd: 76 }, catch: 70,
      learn: [[1, 'cornetazo'], [1, 'bejucazo'], [10, 'serenata'], [16, 'hoja'], [22, 'gaita'], [30, 'monteadentro']],
      dex: 'A las 4 en punto aterriza en tu balcón a cobrar su semilla, como todos los días desde que tu vecino le dio una vez en 2009. No le debas.',
      pal: { k: '#1c1c1c', r: '#d9342b', b: '#2b6bd9', y: '#f5d76e', w: '#ffffff', e: '#222222' },
      art: [
        '.....kkkk.......',
        '....krrrrkk.....',
        '...krrrrrkww....',
        '...krrrrekww....',
        '...krrrrrkkk....',
        '..krrrrrkk......',
        '.kryyrrrrk......',
        '.kryyrrrrbk.....',
        '.krrrrrrbbk.....',
        '..krrrrbbbk.....',
        '...krrrbbk......',
        '....krrbk.......',
        '.....kbbk.......',
        '....kk..kk......',
      ],
    },
    caribito: {
      name: 'Caribito', types: ['Caribe'],
      base: { hp: 38, atk: 52, def: 38, spd: 62 }, catch: 190,
      learn: [[1, 'mordida'], [6, 'aguacerito'], [14, 'paloagua'], [24, 'crecida']],
      evolve: { lvl: 20, to: 'caribazo' },
      dex: 'Pirañita del río. Cayó al Guaire por accidente y salió más fuerte, más rápida y con menos paciencia.',
      pal: { k: '#1c2a33', s: '#6b8fa8', r: '#d9544a', w: '#ffffff', e: '#ffe66e' },
      art: [
        '....kkkkkk......',
        '..kkssssssk.k...',
        '.kssssssssskkk..',
        'ksseksssssssskk.',
        'kssssssssssssk..',
        'kswswswsssskkk..',
        '.krrrrrrssk.kk..',
        '..kkrrrssk...k..',
        '....kkkkk.......',
      ],
    },
    caribazo: {
      name: 'Caribazo', types: ['Caribe'],
      base: { hp: 62, atk: 92, def: 56, spd: 86 }, catch: 60,
      learn: [[1, 'mordida'], [6, 'aguacerito'], [14, 'paloagua'], [24, 'crecida'], [28, 'horapico']],
      dex: 'Lo único que sobrevivió al Guaire, y no solo sobrevivió: puso condiciones. Cuando dicen que van a sanear el río, se ríe con todos los dientes.',
      pal: { k: '#1c2a33', s: '#6b8fa8', r: '#d9544a', w: '#ffffff', e: '#ffe66e' },
      art: [
        '.....kkkkkkk....',
        '...kkssssssssk..',
        '..kssssssssssskk',
        '.ksseksssssssssk',
        '.kssssssssssssskk',
        'kswkwkwkwsssssk.',
        'kskwkwkwkssssskk',
        '.krrrrrrrrssk...',
        '..kkrrrrrrsk.k..',
        '....kkkkkkk.kk..',
      ],
    },
    araguako: {
      name: 'Araguako', types: ['Monte', 'Rumba'],
      base: { hp: 70, atk: 72, def: 56, spd: 50 }, catch: 110,
      learn: [[1, 'trancazo'], [1, 'cornetazo'], [9, 'tambor'], [15, 'bejucazo'], [21, 'gaita'], [29, 'monteadentro'], [33, 'joropo']],
      dex: 'Mono araguato. Su rugido se oye a cinco kilómetros. Tu tía igualito, pero sin megáfono. Comparten repertorio.',
      pal: { k: '#3a1a0a', r: '#b54a2a', t: '#d9824a', m: '#3a1a0a', e: '#222222' },
      art: [
        '....kkkkkkk.....',
        '...krrrrrrrk....',
        '..krtttttttrk...',
        '..krtetttetrk...',
        '..krtttmtttrk...',
        '..krttmmmttrk...',
        '...krrtmtrrk....',
        '..krrrrrrrrkk...',
        '.krrkrrrrkrrk.r.',
        '.krk.rrrr.krk.r.',
        '..k.krrrrk..krr.',
        '....krr.rk......',
        '....kk..kk......',
      ],
    },
    bachaquito: {
      name: 'Bachaquito', types: ['Monte'],
      base: { hp: 40, atk: 56, def: 46, spd: 56 }, catch: 200,
      learn: [[1, 'bejucazo'], [5, 'trancazo'], [10, 'hoja'], [16, 'pedrada'], [24, 'monteadentro']],
      evolve: { lvl: 18, to: 'bachacon' },
      dex: 'Carga cincuenta veces su peso: una hoja, media bolsa de mercado o el orgullo de toda su colonia. Nunca se queja.',
      pal: { k: '#2a1208', r: '#c9502b', g: '#5e8b3f', e: '#ffe66e' },
      art: [
        '..gg............',
        '.gggg...........',
        '..gg.k...k......',
        '...kk.k.k.......',
        '..kerk.krrk.....',
        '..krrkkrrrk.....',
        '...krrrrrrk.....',
        '..krrkrrrrk.....',
        '.k.krrrrk.k.....',
        '..k.kkkk.k......',
      ],
    },
    bachacon: {
      name: 'Bachacón', types: ['Monte', 'Tepuy'],
      base: { hp: 66, atk: 82, def: 72, spd: 58 }, catch: 90,
      learn: [[1, 'bejucazo'], [5, 'trancazo'], [10, 'hoja'], [16, 'pedrada'], [20, 'kueka'], [24, 'monteadentro'], [30, 'tepuyazo']],
      dex: 'Bachaco culón legendario. Construyó su colonia dentro de una pared del Metro y nadie se atreve a cobrarle el condominio.',
      pal: { k: '#2a1208', r: '#c9502b', g: '#5e8b3f', e: '#ffe66e' },
      art: [
        '.gggggg.........',
        'gggggggg........',
        '.gggggg.........',
        '..ggg.kk...kk...',
        '...kkk.k.k.k....',
        '..kerrk.krrrk...',
        '.krrrrkkrrrrrk..',
        '.krrrrrrrrrrrk..',
        '..krrrkrrrrrk...',
        '.k.krrrrrrk.k...',
        '..k.kkkkkk.k....',
      ],
    },
    cachicamo: {
      name: 'Cachicamo', types: ['Tepuy'],
      base: { hp: 56, atk: 60, def: 82, spd: 34 }, catch: 160,
      learn: [[1, 'trancazo'], [1, 'pedrada'], [8, 'kueka'], [14, 'conchazo'], [20, 'temblor'], [30, 'avalancha']],
      dex: 'Cachicamo trabaja pa\' lapa, dice el refrán. Este se cansó: ahora trabaja pa\' él y cotiza su seguro social en piedritas.',
      pal: { k: '#3a2d1e', a: '#b09a6a', d: '#8a754a', p: '#d9b38c', e: '#222222' },
      art: [
        '.....kkkkkkk....',
        '....kaaaaaaak...',
        '...kaadaadaaak..',
        '..kaaadaadaaaak.',
        '..kaaadaadaaaak.',
        '.kaaaadaadaaaak.',
        'kpaaaaaaaaaaaak.',
        'kpekaaaaaaaakk..',
        'kppk.kaaaaak....',
        '.kk..kk..kk.....',
      ],
    },
    morrocoy: {
      name: 'Morrocoy', types: ['Tepuy', 'Sabroso'],
      base: { hp: 86, atk: 56, def: 96, spd: 20 }, catch: 120,
      learn: [[1, 'conchazo'], [1, 'arepazo'], [9, 'kueka'], [16, 'temblor'], [24, 'asadonegro'], [32, 'tepuyazo']],
      dex: 'Le dijo conchudo al cachicamo. El descaro. Vive en el patio de una abuela desde 1974 y conoce todos los secretos de la familia.',
      pal: { k: '#2d2416', g: '#5e6b35', y: '#f5d76e', p: '#c9a36a', e: '#222222' },
      art: [
        '.....kkkkkkk....',
        '....kgyggygk....',
        '..kkgyggyggykk..',
        '.kygygyggygygk..',
        '.kgyggyggyggyk..',
        '.kkkkkkkkkkkkk..',
        'kpek.kppk.kppk..',
        'kppk..kk...kk...',
        '.kk.............',
      ],
    },
    mapanare: {
      name: 'Mapanare', types: ['Monte', 'Espanto'],
      base: { hp: 50, atk: 86, def: 46, spd: 76 }, catch: 110,
      learn: [[1, 'bejucazo'], [1, 'susto'], [9, 'colmillo'], [15, 'maldeojo'], [21, 'monteadentro'], [28, 'nocturno']],
      dex: 'Más peligrosa que mapanare en bolsillo de liqui-liqui. Esta aprendió a viajar en el hueco de los asientos del vagón.',
      pal: { k: '#241a0e', n: '#8a6a3a', d: '#5a4226', e: '#d9d92b', t: '#d9342b' },
      art: [
        '......kkkkk.....',
        '.....knnnnnk....',
        '....knnednnnk...',
        '....knnnnnnkt...',
        '.....knnnnk.t...',
        '..kkkknnnnk.....',
        '.knnnnnnnnk.....',
        'knndnnnndnnk....',
        'knnnnnnnnnnk....',
        '.knndnnnndnk....',
        '..kknnnnnnk.....',
        '....kkkkkk......',
      ],
    },
    duendecito: {
      name: 'Duendecito', types: ['Espanto', 'Monte'],
      base: { hp: 48, atk: 56, def: 56, spd: 50 }, catch: 150,
      learn: [[1, 'susto'], [1, 'bejucazo'], [8, 'pava'], [13, 'llanto'], [19, 'hoja'], [26, 'nocturno']],
      dex: 'Esconde las chancletas izquierdas. Solo las izquierdas. Los científicos no se explican. Las abuelas sí: es él.',
      pal: { k: '#1e1810', h: '#b5300a', f: '#d9a36a', c: '#4a6741', w: '#f2ead8', e: '#222222' },
      art: [
        '.......kk.......',
        '......khhk......',
        '.....khhhhk.....',
        '....khhhhhhk....',
        '...khhhhhhhhk...',
        '...kffeffefk....',
        '....kffffk......',
        '...kcccccck.....',
        '..kcckccckck....',
        '...kccccck......',
        '...kck..kck.....',
        '..kwwk...k......',
      ],
    },
    pavoso: {
      name: 'Pavoso', types: ['Espanto'],
      base: { hp: 66, atk: 42, def: 62, spd: 44 }, catch: 170,
      learn: [[1, 'susto'], [1, 'pava'], [7, 'maldeojo'], [12, 'llanto'], [18, 'nocturno'], [26, 'ultimoviaje']],
      dex: 'Trae la pava. No lo toques, no lo mires, no lo nombres. ¿Ya lo nombraste? Lo siento mucho por tu equipo de béisbol.',
      pal: { k: '#241a33', p: '#6a4a8a', d: '#4a3266', e: '#d9d92b' },
      art: [
        '....kkkkkkk.....',
        '..kkpppppppkk...',
        '.kpppppppppppk..',
        '.kpeppppppepppk.',
        '.kppppkkpppppk..',
        '.kpppppppppppk..',
        '..kpdpdpdpdpk...',
        '..kppdpdpdppk...',
        '...kpppppppk....',
        '..k.kpppppk.k...',
        '.....kkkkk......',
      ],
    },
    vagonima: {
      name: 'Vagónima', types: ['Espanto', 'Catatumbo'],
      base: { hp: 66, atk: 78, def: 66, spd: 78 }, catch: 90,
      learn: [[1, 'susto'], [1, 'chispazo'], [12, 'llanto'], [18, 'corrientazo'], [24, 'nocturno'], [30, 'tercerriel'], [36, 'ultimoviaje']],
      dex: 'El vagón que salió de Propatria en 1987 y nunca llegó a Palo Verde. Sigue en ruta. A veces abre las puertas. No te montes.',
      pal: { k: '#2a2a3a', s: '#c9c9d4', o: '#e85a1a', w: '#aaeeff', e: '#222222' },
      art: [
        '..kkkkkkkkkkkk..',
        '.kssssssssssssk.',
        '.kswwkswwkswwsk.',
        '.kswwkswwkswwsk.',
        '.kssssssssssssk.',
        '.kooooooooooook.',
        '.kssssssssssssk.',
        '..kssssssssssk..',
        '...ss.ssss.ss...',
        '....s..ss..s....',
        '.....s....s.....',
      ],
    },
    llorona: {
      name: 'La Llorona', types: ['Espanto', 'Caribe'],
      base: { hp: 76, atk: 80, def: 60, spd: 64 }, catch: 40,
      learn: [[1, 'llanto'], [1, 'aguacerito'], [14, 'maldeojo'], [20, 'paloagua'], [26, 'nocturno'], [33, 'crecida']],
      dex: 'Llora por las quebradas del Ávila desde hace siglos. En el túnel su llanto se confunde con los frenos del tren. No es el tren.',
      pal: { k: '#1e1e2e', w: '#e8e8f0', f: '#cfcfe0', b: '#8888c9', e: '#222222' },
      art: [
        '.....kkkkkk.....',
        '....kwwwwwwk....',
        '...kwwwwwwwwk...',
        '...kwffffffwk...',
        '...kwfefeffwk...',
        '...kwffffffwk...',
        '...kwffkkffwk...',
        '..kwwffffffwwk..',
        '..kwwwwwwwwwwk..',
        '.b.kwwwwwwwwk.b.',
        '.b.kwwwwwwwwk.b.',
        '..b.kwwwwwwk.b..',
        '....kwwwwwwk....',
        '.....kkkkkk.....',
      ],
    },
    sayona: {
      name: 'La Sayona', types: ['Espanto'],
      base: { hp: 70, atk: 96, def: 60, spd: 82 }, catch: 40,
      learn: [[1, 'susto'], [1, 'maldeojo'], [14, 'llanto'], [20, 'cachetada'], [26, 'nocturno'], [34, 'ultimoviaje']],
      dex: 'Aparece bella en el andén y pregunta por tu situación sentimental. Responde con sinceridad. Es tu única oportunidad.',
      pal: { k: '#111118', h: '#1c1c28', f: '#e0d4c9', e: '#d9342b', d: '#2a2a3a' },
      art: [
        '....kkkkkkkk....',
        '...khhhhhhhhk...',
        '..khhffffffhhk..',
        '..khhfefeffhhk..',
        '..khhffffffhhk..',
        '..khhhfkkfhhhk..',
        '..khhdddddhhhk..',
        '..khdddddddhk...',
        '..khdddddddhk...',
        '...kdddddddk....',
        '...kdddddddk....',
        '..kdddddddddk...',
        '..kdddddddddk...',
        '...kkkkkkkkk....',
      ],
    },
    silbon: {
      name: 'El Silbón', types: ['Espanto', 'Rumba'],
      base: { hp: 80, atk: 105, def: 70, spd: 95 }, catch: 15,
      learn: [[1, 'silbido'], [1, 'pava'], [22, 'nocturno'], [30, 'joropo'], [38, 'ultimoviaje']],
      dex: 'Carga un saco de huesos y silba toditas las noches. Si lo oyes lejos, está cerca. Si lo oyes cerca... saluda con respeto.',
      pal: { k: '#15151c', h: '#3a3226', f: '#cfc0a8', d: '#26262e', s: '#8a754a', e: '#ffffff' },
      art: [
        '.....hhhhhh.....',
        '...hhhhhhhhhh...',
        '.....kffffk.....',
        '.....kfefek.....',
        '.....kffffk.....',
        '......kffk......',
        '....kkddddkk....',
        '...kd.kddk.dk...',
        '...k..kddk..k...',
        '..ss..kddk......',
        '.ssss.kddk......',
        '.ssss.kdkdk.....',
        '..ss..kk.kk.....',
        '......k...k.....',
      ],
    },
    catatumbo: {
      name: 'Catatumbo', types: ['Catatumbo', 'Caribe'],
      base: { hp: 86, atk: 110, def: 76, spd: 100 }, catch: 15,
      learn: [[1, 'chispazo'], [1, 'paloagua'], [20, 'corrientazo'], [28, 'crecida'], [35, 'catatumbazo']],
      dex: 'El relámpago eterno del Lago de Maracaibo, faro natural del Caribe. Un día bajó a Caracas en tren a ver qué era el corre-corre.',
      pal: { k: '#2a2a3a', c: '#5a6a7a', w: '#3b6b8c', y: '#ffe66e', e: '#ffffff' },
      art: [
        '...kkkkkkkkkk...',
        '..kcccccccccck..',
        '.kcccccccccccck.',
        '.kccecccccecck..',
        '..kcccccccccck..',
        '...kkkkkkkkkk...',
        '....y...y..y....',
        '...yy..yy..y....',
        '...y...y..yy....',
        '..yy..yy..y.....',
        '..wwwwwwwwwww...',
        '.wwwwwwwwwwwww..',
      ],
    },
    trenfantasma: {
      name: 'Tren Fantasma', types: ['Espanto', 'Catatumbo'],
      base: { hp: 100, atk: 88, def: 82, spd: 78 }, catch: 5,
      learn: [[1, 'nocturno'], [1, 'tercerriel'], [30, 'ultimoviaje'], [40, 'catatumbazo']],
      dex: 'El primer tren del 83 nunca fue desincorporado: fue olvidado. Y lo olvidado, en Caracas, no muere — hace estación propia.',
      pal: { k: '#0e0e16', s: '#3a3a4a', o: '#e85a1a', w: '#ffe66e', g: '#7affc9', e: '#222222' },
      art: [
        '...kkkkkkkkkk...',
        '..kssssssssssk..',
        '.kskwwkssskwwsk.',
        '.kskwwkssskwwsk.',
        '.kssssssssssssk.',
        '.ksoooooooooosk.',
        '.kssssksksssssk.',
        '.kssssssssssssk.',
        '.kskgks..kgkssk.',
        '..kwk......kwk..',
        '.gg.g.gggg.g.gg.',
        '..g..gg..gg..g..',
      ],
    },
  };

  MQ.DEX_ORDER = [
    'arepito', 'pepiada', 'turpialin', 'cantaclaro', 'cocuyin', 'centella',
    'chigui', 'chiguiron', 'guacamayo', 'caribito', 'caribazo', 'araguako',
    'bachaquito', 'bachacon', 'cachicamo', 'morrocoy', 'mapanare', 'duendecito',
    'pavoso', 'vagonima', 'llorona', 'sayona', 'silbon', 'catatumbo', 'trenfantasma',
  ];

  // ---- Cálculos -------------------------------------------------------------
  MQ.xpForLevel = (l) => l * l * l;

  MQ.calcStats = (id, lvl) => {
    const b = MQ.SPECIES[id].base;
    return {
      hp:  Math.floor((b.hp * 2 * lvl) / 100) + lvl + 10,
      atk: Math.floor((b.atk * 2 * lvl) / 100) + 5,
      def: Math.floor((b.def * 2 * lvl) / 100) + 5,
      spd: Math.floor((b.spd * 2 * lvl) / 100) + 5,
    };
  };

  MQ.movesAtLevel = (id, lvl) =>
    MQ.SPECIES[id].learn.filter(([l]) => l <= lvl).map(([, m]) => m).slice(-4);

  MQ.makeMon = (id, lvl) => {
    const st = MQ.calcStats(id, lvl);
    return { id, lvl, xp: MQ.xpForLevel(lvl), hp: st.hp, maxhp: st.hp, atk: st.atk, def: st.def, spd: st.spd, moves: MQ.movesAtLevel(id, lvl) };
  };

  MQ.expYield = (id) => {
    const b = MQ.SPECIES[id].base;
    return Math.round((b.hp + b.atk + b.def + b.spd) * 0.45);
  };

  // ---- Ítems ----------------------------------------------------------------
  MQ.ITEMS = {
    ficha:    { name: 'Ficha del Metro',  price: 30,  desc: 'Ficha amarilla del 83. Lánzala para fichar un espanto salvaje.', ball: 1 },
    fichaplus:{ name: 'Ficha Dorada',     price: 150, desc: 'Ficha conmemorativa pulida con Brasso. Los espantos la respetan.', ball: 1.8 },
    fichaoro: { name: 'Ficha de Oro',     price: 0,   desc: 'Bendecida en la montaña de Sorte. No falla jamás.', ball: 255 },
    malta:    { name: 'Maltín frío',      price: 20,  desc: 'Restaura 30 PS. La merienda de los campeones.', heal: 30 },
    cafe:     { name: 'Marroncito',       price: 45,  desc: 'Restaura 70 PS. Oscuro, dulce y de máquina de estación.', heal: 70 },
    golfeado: { name: 'Golfeado',         price: 90,  desc: 'Restaura todos los PS. Con queso de mano encima, obvio.', heal: 9999 },
    cocada:   { name: 'Cocada',           price: 120, desc: 'Revive a un espanto debilitado con la mitad de sus PS.', revive: 0.5 },
  };
})();
