#!/usr/bin/env python3
"""Scan assets/creatures and emit js/sprite-manifest.js — the list of which
PNG sprite kinds exist per species, so the engine knows when to use real
sprites vs. fall back to the procedural pixel art. Regenerate after adding art."""
import os, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets", "creatures")
KINDS = {
    "front": "front.png",
    "back": "back.png",
    "icon": "icon.png",
    "overworld": "overworld.png",
    "shiny": "front-tornasol.png",
}

manifest = {}
for cid in sorted(os.listdir(ASSETS)):
    d = os.path.join(ASSETS, cid)
    if not os.path.isdir(d):
        continue
    kinds = {k: 1 for k, fn in KINDS.items() if os.path.isfile(os.path.join(d, fn))}
    if kinds.get("front"):  # only species that have at least a battle sprite
        manifest[cid] = kinds

out = os.path.join(ROOT, "js", "sprite-manifest.js")
with open(out, "w") as f:
    f.write("// AUTO-GENERATED by scripts/build_sprite_manifest.py — do not edit by hand.\n")
    f.write("// Which PNG sprite kinds exist per species (front/back/icon/overworld/shiny).\n")
    f.write("// The engine uses these real sprites and falls back to procedural art otherwise.\n")
    f.write("(() => {\n  const MQ = (globalThis.MQ = globalThis.MQ || {});\n")
    f.write("  MQ.SPRITE_ASSETS = " + json.dumps(manifest, separators=(",", ":")) + ";\n")
    f.write("})();\n")

print(f"wrote {out}: {len(manifest)} species with sprites")
