#!/usr/bin/env python3
"""Compile data/*.json into js/gamedata.js (MQ.DATA).

The game is zero-dependency and must open from file:// — no fetch(). This
compiles the Phase 1-4 data deliverables (creatures, moves, abilities,
encounters) into one generated script loaded before js/dex.js. Regenerate
after any data change: python3 scripts/build_gamedata.py
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def load(rel):
    with open(os.path.join(ROOT, "data", rel), encoding="utf-8") as fh:
        return json.load(fh)

creatures = load("creatures/creatures.json")
moves = load("moves/moves.json")
abilities = load("abilities/abilities.json")
encounters = load("encounters/encounters.json")

data = {
    "creatures": creatures["creatures"],
    "moves": moves["moves"],
    "abilities": abilities["abilities"],
    "encounters": {
        "tables": encounters["tables"],
        "static": encounters["static"],
        "gifts": encounters["gifts"],
        "roaming": encounters["roaming"],
    },
}

out = os.path.join(ROOT, "js", "gamedata.js")
with open(out, "w", encoding="utf-8") as f:
    f.write("// AUTO-GENERATED by scripts/build_gamedata.py — do not edit by hand.\n")
    f.write("// Compiled from data/creatures, data/moves, data/abilities, data/encounters.\n")
    f.write("(() => {\n  const MQ = (globalThis.MQ = globalThis.MQ || {});\n")
    f.write("  MQ.DATA = ")
    f.write(json.dumps(data, ensure_ascii=False, separators=(",", ":")))
    f.write(";\n})();\n")

size = os.path.getsize(out)
print(f"wrote js/gamedata.js ({size//1024} KB): "
      f"{len(data['creatures'])} creatures, {len(data['moves'])} moves, "
      f"{len(data['abilities'])} abilities, {len(data['encounters']['tables'])} tables")
